### ISSUE TITLE
Brak bilbioteki w classpath

### ISSUE THREAD

**Issue by RadoslawBiereta** [annadrobek/ShoppingList#19]
java.net.URLClassLoader@23ab930d
]
                at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:483)
                at org.springframework.util.ReflectionUtils.doWithLocalMethods(ReflectionUtils.java:320)
                at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.checkLookupMethods(AutowiredAnnotationBeanPostProcessor.java:448)
                ... 60 more
        Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/configurationprocessor/json/JSONException
                at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
                at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402)
                at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504)
                at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:465)
                ... 62 more
        Caused by: java.lang.ClassNotFoundException: org.springframework.boot.configurationprocessor.json.JSONException
                at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1437)
                at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1245)
                ... 66 more

**Comment by annadrobek** [comment]
Problem został rozwiązany

**Comment by annadrobek** [comment]
powinno być już ok
